export interface CountryProfile {
  code: string;
  name: string;
  flag: string;
  continent: 'Africa' | 'Asia' | 'Europe' | 'North America' | 'South America' | 'Oceania';
  currency: string;
  crops: string[];
  diseases: string[];
}

// 40 detailed profiles representing major global regions, plus programmatic fallbacks to complete the 195 country requirement.
export const MAJOR_COUNTRIES: CountryProfile[] = [
  { code: 'IN', name: 'India', flag: '🇮🇳', continent: 'Asia', currency: 'INR', crops: ['Tomato', 'Rice', 'Wheat', 'Cotton', 'Mango'], diseases: ['Tomato Early Blight', 'Rice Blast', 'Wheat Rust'] },
  { code: 'KE', name: 'Kenya', flag: '🇰🇪', continent: 'Africa', currency: 'KES', crops: ['Maize', 'Coffee', 'Potato', 'Banana'], diseases: ['Potato Late Blight', 'Maize Smut'] },
  { code: 'US', name: 'United States', flag: '🇺🇸', continent: 'North America', currency: 'USD', crops: ['Maize', 'Soybean', 'Wheat', 'Potato', 'Grapes'], diseases: ['Potato Late Blight', 'Wheat Rust'] },
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', continent: 'South America', currency: 'BRL', crops: ['Soybean', 'Coffee', 'Citrus', 'Maize'], diseases: ['Citrus Canker', 'Maize Smut'] },
  { code: 'CN', name: 'China', flag: '🇨🇳', continent: 'Asia', currency: 'CNY', crops: ['Rice', 'Wheat', 'Maize', 'Tomato', 'Citrus'], diseases: ['Rice Blast', 'Tomato Early Blight'] },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', continent: 'Africa', currency: 'NGN', crops: ['Maize', 'Banana', 'Soybean', 'Citrus'], diseases: ['Maize Smut'] },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', continent: 'Oceania', currency: 'AUD', crops: ['Wheat', 'Grapes', 'Citrus', 'Cotton'], diseases: ['Wheat Rust'] },
  { code: 'ZA', name: 'South Africa', flag: '🇿🇦', continent: 'Africa', currency: 'ZAR', crops: ['Citrus', 'Maize', 'Grapes', 'Wheat'], diseases: ['Wheat Rust', 'Citrus Canker'] },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', continent: 'South America', currency: 'ARS', crops: ['Soybean', 'Wheat', 'Maize', 'Citrus'], diseases: ['Wheat Rust', 'Maize Smut'] },
  { code: 'EG', name: 'Egypt', flag: '🇪🇬', continent: 'Africa', currency: 'EGP', crops: ['Wheat', 'Tomato', 'Orange', 'Onion'], diseases: ['Tomato Early Blight'] },
  { code: 'FR', name: 'France', flag: '🇫🇷', continent: 'Europe', currency: 'EUR', crops: ['Wheat', 'Grapes', 'Potato', 'Citrus'], diseases: ['Wheat Rust', 'Potato Late Blight'] },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', continent: 'Europe', currency: 'EUR', crops: ['Wheat', 'Potato', 'Onion', 'Grapes'], diseases: ['Potato Late Blight'] },
  { code: 'IT', name: 'Italy', flag: '🇮🇹', continent: 'Europe', currency: 'EUR', crops: ['Grapes', 'Tomato', 'Citrus', 'Wheat'], diseases: ['Tomato Early Blight'] },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', continent: 'Europe', currency: 'EUR', crops: ['Citrus', 'Grapes', 'Tomato', 'Onion'], diseases: ['Tomato Early Blight'] },
  { code: 'GB', name: 'United Kingdom', flag: '🇬🇧', continent: 'Europe', currency: 'GBP', crops: ['Wheat', 'Potato', 'Onion'], diseases: ['Potato Late Blight'] },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', continent: 'North America', currency: 'MXN', crops: ['Maize', 'Tomato', 'Pepper', 'Coffee'], diseases: ['Tomato Early Blight'] },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', continent: 'Asia', currency: 'JPY', crops: ['Rice', 'Citrus', 'Tomato', 'Onion'], diseases: ['Rice Blast'] },
  { code: 'BD', name: 'Bangladesh', flag: '🇧🇩', continent: 'Asia', currency: 'BDT', crops: ['Rice', 'Potato', 'Wheat', 'Mango'], diseases: ['Rice Blast', 'Potato Late Blight'] },
  { code: 'VN', name: 'Vietnam', flag: '🇻🇳', continent: 'Asia', currency: 'VND', crops: ['Rice', 'Coffee', 'Banana', 'Pepper'], diseases: ['Rice Blast'] },
  { code: 'PK', name: 'Pakistan', flag: '🇵🇰', continent: 'Asia', currency: 'PKR', crops: ['Wheat', 'Rice', 'Cotton', 'Citrus'], diseases: ['Wheat Rust', 'Rice Blast'] },
  { code: 'ID', name: 'Indonesia', flag: '🇮🇩', continent: 'Asia', currency: 'IDR', crops: ['Rice', 'Coffee', 'Banana', 'Citrus'], diseases: ['Rice Blast'] },
  { code: 'TR', name: 'Turkey', flag: '🇹🇷', continent: 'Asia', currency: 'TRY', crops: ['Wheat', 'Tomato', 'Grapes', 'Onion'], diseases: ['Tomato Early Blight'] },
  { code: 'CA', name: 'Canada', flag: '🇨🇦', continent: 'North America', currency: 'CAD', crops: ['Wheat', 'Soybean', 'Potato', 'Onion'], diseases: ['Wheat Rust'] },
  { code: 'UA', name: 'Ukraine', flag: '🇺🇦', continent: 'Europe', currency: 'UAH', crops: ['Wheat', 'Maize', 'Soybean', 'Potato'], diseases: ['Wheat Rust'] },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', continent: 'South America', currency: 'COP', crops: ['Coffee', 'Banana', 'Rice', 'Citrus'], diseases: ['Rice Blast'] },
  { code: 'PH', name: 'Philippines', flag: '🇵🇭', continent: 'Asia', currency: 'PHP', crops: ['Rice', 'Banana', 'Citrus', 'Coffee'], diseases: ['Rice Blast'] },
  { code: 'TH', name: 'Thailand', flag: '🇹🇭', continent: 'Asia', currency: 'THB', crops: ['Rice', 'Citrus', 'Banana', 'Maize'], diseases: ['Rice Blast'] },
  { code: 'ET', name: 'Ethiopia', flag: '🇪🇹', continent: 'Africa', currency: 'ETB', crops: ['Coffee', 'Wheat', 'Maize', 'Potato'], diseases: ['Wheat Rust'] },
  { code: 'GH', name: 'Ghana', flag: '🇬🇭', continent: 'Africa', currency: 'GHS', crops: ['Banana', 'Maize', 'Citrus', 'Rice'], diseases: ['Maize Smut'] },
  { code: 'UG', name: 'Uganda', flag: '🇺🇬', continent: 'Africa', currency: 'UGX', crops: ['Banana', 'Coffee', 'Maize', 'Potato'], diseases: ['Potato Late Blight'] },
  { code: 'TZ', name: 'Tanzania', flag: '🇹🇿', continent: 'Africa', currency: 'TZS', crops: ['Maize', 'Coffee', 'Banana', 'Wheat'], diseases: ['Maize Smut'] },
  { code: 'PE', name: 'Peru', flag: '🇵🇪', continent: 'South America', currency: 'PEN', crops: ['Potato', 'Coffee', 'Grapes', 'Citrus'], diseases: ['Potato Late Blight'] },
  { code: 'CL', name: 'Chile', flag: '🇨🇱', continent: 'South America', currency: 'CLP', crops: ['Grapes', 'Citrus', 'Wheat', 'Tomato'], diseases: ['Tomato Early Blight'] },
  { code: 'NZ', name: 'New Zealand', flag: '🇳🇿', continent: 'Oceania', currency: 'NZD', crops: ['Grapes', 'Citrus', 'Wheat', 'Potato'], diseases: ['Potato Late Blight'] },
  { code: 'NL', name: 'Netherlands', flag: '🇳🇱', continent: 'Europe', currency: 'EUR', crops: ['Potato', 'Tomato', 'Onion'], diseases: ['Potato Late Blight'] },
  { code: 'PL', name: 'Poland', flag: '🇵🇱', continent: 'Europe', currency: 'PLN', crops: ['Wheat', 'Potato', 'Onion'], diseases: ['Potato Late Blight'] },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', continent: 'Africa', currency: 'MAD', crops: ['Wheat', 'Citrus', 'Tomato', 'Onion'], diseases: ['Tomato Early Blight'] },
  { code: 'DZ', name: 'Algeria', flag: '🇩🇿', continent: 'Africa', currency: 'DZD', crops: ['Wheat', 'Potato', 'Citrus', 'Onion'], diseases: ['Potato Late Blight'] },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', continent: 'Asia', currency: 'SAR', crops: ['Citrus', 'Tomato', 'Onion'], diseases: ['Tomato Early Blight'] },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', continent: 'Asia', currency: 'KRW', crops: ['Rice', 'Citrus', 'Onion', 'Grapes'], diseases: ['Rice Blast'] }
];

// ISO codes for all 195 countries to fill out database
export const ALL_COUNTRY_CODES: { [code: string]: { name: string, flag: string, continent: 'Africa' | 'Asia' | 'Europe' | 'North America' | 'South America' | 'Oceania' } } = {
  AF: { name: 'Afghanistan', flag: '🇦🇫', continent: 'Asia' },
  AL: { name: 'Albania', flag: '🇦🇱', continent: 'Europe' },
  DZ: { name: 'Algeria', flag: '🇩🇿', continent: 'Africa' },
  AD: { name: 'Andorra', flag: '🇦🇩', continent: 'Europe' },
  AO: { name: 'Angola', flag: '🇦🇴', continent: 'Africa' },
  AG: { name: 'Antigua and Barbuda', flag: '🇦🇬', continent: 'North America' },
  AR: { name: 'Argentina', flag: '🇦🇷', continent: 'South America' },
  AM: { name: 'Armenia', flag: '🇦🇲', continent: 'Asia' },
  AU: { name: 'Australia', flag: '🇦🇺', continent: 'Oceania' },
  AT: { name: 'Austria', flag: '🇦🇹', continent: 'Europe' },
  AZ: { name: 'Azerbaijan', flag: '🇦🇿', continent: 'Asia' },
  BS: { name: 'Bahamas', flag: '🇧🇸', continent: 'North America' },
  BH: { name: 'Bahrain', flag: '🇧🇭', continent: 'Asia' },
  BD: { name: 'Bangladesh', flag: '🇧🇩', continent: 'Asia' },
  BB: { name: 'Barbados', flag: '🇧🇧', continent: 'North America' },
  BY: { name: 'Belarus', flag: '🇧🇾', continent: 'Europe' },
  BE: { name: 'Belgium', flag: '🇧🇪', continent: 'Europe' },
  BZ: { name: 'Belize', flag: '🇧🇿', continent: 'North America' },
  BJ: { name: 'Benin', flag: '🇧🇯', continent: 'Africa' },
  BT: { name: 'Bhutan', flag: '🇧🇹', continent: 'Asia' },
  BO: { name: 'Bolivia', flag: '🇧🇴', continent: 'South America' },
  BA: { name: 'Bosnia and Herzegovina', flag: '🇧🇦', continent: 'Europe' },
  BW: { name: 'Botswana', flag: '🇧🇼', continent: 'Africa' },
  BR: { name: 'Brazil', flag: '🇧🇷', continent: 'South America' },
  BN: { name: 'Brunei', flag: '🇧🇳', continent: 'Asia' },
  BG: { name: 'Bulgaria', flag: '🇧🇬', continent: 'Europe' },
  BF: { name: 'Burkina Faso', flag: '🇧🇫', continent: 'Africa' },
  BI: { name: 'Burundi', flag: '🇧🇮', continent: 'Africa' },
  KH: { name: 'Cambodia', flag: '🇰🇭', continent: 'Asia' },
  CM: { name: 'Cameroon', flag: '🇨🇲', continent: 'Africa' },
  CA: { name: 'Canada', flag: '🇨🇦', continent: 'North America' },
  CV: { name: 'Cape Verde', flag: '🇨🇻', continent: 'Africa' },
  CF: { name: 'Central African Republic', flag: '🇨🇫', continent: 'Africa' },
  TD: { name: 'Chad', flag: '🇹🇩', continent: 'Africa' },
  CL: { name: 'Chile', flag: '🇨🇱', continent: 'South America' },
  CN: { name: 'China', flag: '🇨🇳', continent: 'Asia' },
  CO: { name: 'Colombia', flag: '🇨🇴', continent: 'South America' },
  KM: { name: 'Comoros', flag: '🇰🇲', continent: 'Africa' },
  CG: { name: 'Congo', flag: '🇨🇬', continent: 'Africa' },
  CR: { name: 'Costa Rica', flag: '🇨🇷', continent: 'North America' },
  HR: { name: 'Croatia', flag: '🇭🇷', continent: 'Europe' },
  CU: { name: 'Cuba', flag: '🇨🇺', continent: 'North America' },
  CY: { name: 'Cyprus', flag: '🇨🇾', continent: 'Asia' },
  CZ: { name: 'Czech Republic', flag: '🇨🇿', continent: 'Europe' },
  CD: { name: 'Democratic Republic of the Congo', flag: '🇨🇩', continent: 'Africa' },
  DK: { name: 'Denmark', flag: '🇩🇰', continent: 'Europe' },
  DJ: { name: 'Djibouti', flag: '🇩🇯', continent: 'Africa' },
  DM: { name: 'Dominica', flag: '🇩🇲', continent: 'North America' },
  DO: { name: 'Dominican Republic', flag: '🇩🇴', continent: 'North America' },
  EC: { name: 'Ecuador', flag: '🇪🇨', continent: 'South America' },
  EG: { name: 'Egypt', flag: '🇪🇬', continent: 'Africa' },
  SV: { name: 'El Salvador', flag: '🇸🇻', continent: 'North America' },
  GQ: { name: 'Equatorial Guinea', flag: '🇬🇶', continent: 'Africa' },
  ER: { name: 'Eritrea', flag: '🇪🇷', continent: 'Africa' },
  EE: { name: 'Estonia', flag: '🇪🇪', continent: 'Europe' },
  SZ: { name: 'Eswatini', flag: '🇸🇿', continent: 'Africa' },
  ET: { name: 'Ethiopia', flag: '🇪🇹', continent: 'Africa' },
  FJ: { name: 'Fiji', flag: '🇫🇯', continent: 'Oceania' },
  FI: { name: 'Finland', flag: '🇫🇮', continent: 'Europe' },
  FR: { name: 'France', flag: '🇫🇷', continent: 'Europe' },
  GA: { name: 'Gabon', flag: '🇬🇦', continent: 'Africa' },
  GM: { name: 'Gambia', flag: '🇬🇲', continent: 'Africa' },
  GE: { name: 'Georgia', flag: '🇬🇪', continent: 'Asia' },
  DE: { name: 'Germany', flag: '🇩🇪', continent: 'Europe' },
  GH: { name: 'Ghana', flag: '🇬🇭', continent: 'Africa' },
  GR: { name: 'Greece', flag: '🇬🇷', continent: 'Europe' },
  GD: { name: 'Grenada', flag: '🇬🇩', continent: 'North America' },
  GT: { name: 'Guatemala', flag: '🇬🇹', continent: 'North America' },
  GN: { name: 'Guinea', flag: '🇬🇳', continent: 'Africa' },
  GW: { name: 'Guinea-Bissau', flag: '🇬🇼', continent: 'Africa' },
  GY: { name: 'Guyana', flag: '🇬🇾', continent: 'South America' },
  HT: { name: 'Haiti', flag: '🇭🇹', continent: 'North America' },
  HN: { name: 'Honduras', flag: '🇭🇳', continent: 'North America' },
  HU: { name: 'Hungary', flag: '🇭🇺', continent: 'Europe' },
  IS: { name: 'Iceland', flag: '🇮🇸', continent: 'Europe' },
  IN: { name: 'India', flag: '🇮🇳', continent: 'Asia' },
  ID: { name: 'Indonesia', flag: '🇮🇩', continent: 'Asia' },
  IR: { name: 'Iran', flag: '🇮🇷', continent: 'Asia' },
  IQ: { name: 'Iraq', flag: '🇮🇶', continent: 'Asia' },
  IE: { name: 'Ireland', flag: '🇮🇪', continent: 'Europe' },
  IL: { name: 'Israel', flag: '🇮🇱', continent: 'Asia' },
  IT: { name: 'Italy', flag: '🇮🇹', continent: 'Europe' },
  CI: { name: 'Ivory Coast', flag: '🇨🇮', continent: 'Africa' },
  JM: { name: 'Jamaica', flag: '🇯🇲', continent: 'North America' },
  JP: { name: 'Japan', flag: '🇯🇵', continent: 'Asia' },
  JO: { name: 'Jordan', flag: '🇯🇴', continent: 'Asia' },
  KZ: { name: 'Kazakhstan', flag: '🇰🇿', continent: 'Asia' },
  KE: { name: 'Kenya', flag: '🇰🇪', continent: 'Africa' },
  KI: { name: 'Kiribati', flag: '🇰🇮', continent: 'Oceania' },
  KP: { name: 'North Korea', flag: '🇰🇵', continent: 'Asia' },
  KR: { name: 'South Korea', flag: '🇰🇷', continent: 'Asia' },
  KW: { name: 'Kuwait', flag: '🇰🇼', continent: 'Asia' },
  KG: { name: 'Kyrgyzstan', flag: '🇰🇬', continent: 'Asia' },
  LA: { name: 'Laos', flag: '🇱🇦', continent: 'Asia' },
  LV: { name: 'Latvia', flag: '🇱🇻', continent: 'Europe' },
  LB: { name: 'Lebanon', flag: '🇱🇧', continent: 'Asia' },
  LS: { name: 'Lesotho', flag: '🇱🇸', continent: 'Africa' },
  LR: { name: 'Liberia', flag: '🇱🇷', continent: 'Africa' },
  LY: { name: 'Libya', flag: '🇱🇾', continent: 'Africa' },
  LI: { name: 'Liechtenstein', flag: '🇱🇮', continent: 'Europe' },
  LT: { name: 'Lithuania', flag: '🇱🇹', continent: 'Europe' },
  LU: { name: 'Luxembourg', flag: '🇱🇺', continent: 'Europe' },
  MG: { name: 'Madagascar', flag: '🇲🇬', continent: 'Africa' },
  MW: { name: 'Malawi', flag: '🇲🇼', continent: 'Africa' },
  MY: { name: 'Malaysia', flag: '🇲🇾', continent: 'Asia' },
  MV: { name: 'Maldives', flag: '🇲🇻', continent: 'Asia' },
  ML: { name: 'Mali', flag: '🇲🇱', continent: 'Africa' },
  MT: { name: 'Malta', flag: '🇲🇹', continent: 'Europe' },
  MH: { name: 'Marshall Islands', flag: '🇲🇭', continent: 'Oceania' },
  MR: { name: 'Mauritania', flag: '🇲🇷', continent: 'Africa' },
  MU: { name: 'Mauritius', flag: '🇲🇺', continent: 'Africa' },
  MX: { name: 'Mexico', flag: '🇲🇽', continent: 'North America' },
  FM: { name: 'Micronesia', flag: '🇫🇲', continent: 'Oceania' },
  MD: { name: 'Moldova', flag: '🇲🇩', continent: 'Europe' },
  MC: { name: 'Monaco', flag: '🇲🇨', continent: 'Europe' },
  MN: { name: 'Mongolia', flag: '🇲🇳', continent: 'Asia' },
  ME: { name: 'Montenegro', flag: '🇲🇪', continent: 'Europe' },
  MA: { name: 'Morocco', flag: '🇲🇦', continent: 'Africa' },
  MZ: { name: 'Mozambique', flag: '🇲🇿', continent: 'Africa' },
  MM: { name: 'Myanmar', flag: '🇲🇲', continent: 'Asia' },
  NA: { name: 'Namibia', flag: '🇳🇦', continent: 'Africa' },
  NR: { name: 'Nauru', flag: '🇳🇷', continent: 'Oceania' },
  NP: { name: 'Nepal', flag: '🇳🇵', continent: 'Asia' },
  NL: { name: 'Netherlands', flag: '🇳🇱', continent: 'Europe' },
  NZ: { name: 'New Zealand', flag: '🇳🇿', continent: 'Oceania' },
  NI: { name: 'Nicaragua', flag: '🇳🇮', continent: 'North America' },
  NE: { name: 'Niger', flag: '🇳🇪', continent: 'Africa' },
  NG: { name: 'Nigeria', flag: '🇳🇬', continent: 'Africa' },
  MK: { name: 'North Macedonia', flag: '🇲🇰', continent: 'Europe' },
  NO: { name: 'Norway', flag: '🇳🇴', continent: 'Europe' },
  OM: { name: 'Oman', flag: '🇴🇲', continent: 'Asia' },
  PK: { name: 'Pakistan', flag: '🇵🇰', continent: 'Asia' },
  PW: { name: 'Palau', flag: '🇵🇼', continent: 'Oceania' },
  PA: { name: 'Panama', flag: '🇵🇦', continent: 'North America' },
  PG: { name: 'Papua New Guinea', flag: '🇵🇬', continent: 'Oceania' },
  PY: { name: 'Paraguay', flag: '🇵🇾', continent: 'South America' },
  PE: { name: 'Peru', flag: '🇵🇪', continent: 'South America' },
  PH: { name: 'Philippines', flag: '🇵🇭', continent: 'Asia' },
  PL: { name: 'Poland', flag: '🇵🇱', continent: 'Europe' },
  PT: { name: 'Portugal', flag: '🇵🇹', continent: 'Europe' },
  QA: { name: 'Qatar', flag: '🇶🇦', continent: 'Asia' },
  RO: { name: 'Romania', flag: '🇷🇴', continent: 'Europe' },
  RU: { name: 'Russia', flag: '🇷🇺', continent: 'Europe' },
  RW: { name: 'Rwanda', flag: '🇷🇼', continent: 'Africa' },
  KN: { name: 'Saint Kitts and Nevis', flag: '🇰🇳', continent: 'North America' },
  LC: { name: 'Saint Lucia', flag: '🇱🇨', continent: 'North America' },
  VC: { name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', continent: 'North America' },
  WS: { name: 'Samoa', flag: '🇼🇸', continent: 'Oceania' },
  SM: { name: 'San Marino', flag: '🇸🇲', continent: 'Europe' },
  ST: { name: 'Sao Tome and Principe', flag: '🇸🇹', continent: 'Africa' },
  SA: { name: 'Saudi Arabia', flag: '🇸🇦', continent: 'Asia' },
  SN: { name: 'Senegal', flag: '🇸🇳', continent: 'Africa' },
  RS: { name: 'Serbia', flag: '🇷🇸', continent: 'Europe' },
  SC: { name: 'Seychelles', flag: '🇸🇨', continent: 'Africa' },
  SL: { name: 'Sierra Leone', flag: '🇸🇱', continent: 'Africa' },
  SG: { name: 'Singapore', flag: '🇸🇬', continent: 'Asia' },
  SK: { name: 'Slovakia', flag: '🇸🇰', continent: 'Europe' },
  SI: { name: 'Slovenia', flag: '🇸🇮', continent: 'Europe' },
  SB: { name: 'Solomon Islands', flag: '🇸🇧', continent: 'Oceania' },
  SO: { name: 'Somalia', flag: '🇸🇴', continent: 'Africa' },
  ZA: { name: 'South Africa', flag: '🇿🇦', continent: 'Africa' },
  SS: { name: 'South Sudan', flag: '🇸🇸', continent: 'Africa' },
  ES: { name: 'Spain', flag: '🇪🇸', continent: 'Europe' },
  LK: { name: 'Sri Lanka', flag: '🇱🇰', continent: 'Asia' },
  SD: { name: 'Sudan', flag: '🇸🇩', continent: 'Africa' },
  SR: { name: 'Suriname', flag: '🇸🇷', continent: 'South America' },
  SE: { name: 'Sweden', flag: '🇸🇪', continent: 'Europe' },
  CH: { name: 'Switzerland', flag: '🇨🇭', continent: 'Europe' },
  SY: { name: 'Syria', flag: '🇸🇾', continent: 'Asia' },
  TJ: { name: 'Tajikistan', flag: '🇹🇯', continent: 'Asia' },
  TZ: { name: 'Tanzania', flag: '🇹🇿', continent: 'Africa' },
  TH: { name: 'Thailand', flag: '🇹🇭', continent: 'Asia' },
  TL: { name: 'Timor-Leste', flag: '🇹🇱', continent: 'Asia' },
  TG: { name: 'Togo', flag: '🇹🇬', continent: 'Africa' },
  TO: { name: 'Tonga', flag: '🇹🇴', continent: 'Oceania' },
  TT: { name: 'Trinidad and Tobago', flag: '🇹🇹', continent: 'North America' },
  TN: { name: 'Tunisia', flag: '🇹🇳', continent: 'Africa' },
  TR: { name: 'Turkey', flag: '🇹🇷', continent: 'Asia' },
  TM: { name: 'Turkmenistan', flag: '🇹🇲', continent: 'Asia' },
  TV: { name: 'Tuvalu', flag: '🇹🇻', continent: 'Oceania' },
  UG: { name: 'Uganda', flag: '🇺🇬', continent: 'Africa' },
  UA: { name: 'Ukraine', flag: '🇺🇦', continent: 'Europe' },
  AE: { name: 'United Arab Emirates', flag: '🇦🇪', continent: 'Asia' },
  GB: { name: 'United Kingdom', flag: '🇬🇧', continent: 'Europe' },
  US: { name: 'United States', flag: '🇺🇸', continent: 'North America' },
  UY: { name: 'Uruguay', flag: '🇺🇾', continent: 'South America' },
  UZ: { name: 'Uzbekistan', flag: '🇺🇿', continent: 'Asia' },
  VU: { name: 'Vanuatu', flag: '🇻🇺', continent: 'Oceania' },
  VE: { name: 'Venezuela', flag: '🇻🇪', continent: 'South America' },
  VN: { name: 'Vietnam', flag: '🇻🇳', continent: 'Asia' },
  YE: { name: 'Yemen', flag: '🇾🇪', continent: 'Asia' },
  ZM: { name: 'Zambia', flag: '🇿🇲', continent: 'Africa' },
  ZW: { name: 'Zimbabwe', flag: '🇿🇼', continent: 'Africa' }
};

export const getCountriesList = (): CountryProfile[] => {
  const list: CountryProfile[] = [];
  
  Object.keys(ALL_COUNTRY_CODES).forEach((code) => {
    const existing = MAJOR_COUNTRIES.find((c) => c.code === code);
    if (existing) {
      list.push(existing);
    } else {
      const data = ALL_COUNTRY_CODES[code];
      list.push({
        code,
        name: data.name,
        flag: data.flag,
        continent: data.continent,
        currency: 'USD',
        crops: ['Maize', 'Potato', 'Wheat'],
        diseases: ['Maize Smut', 'Potato Late Blight']
      });
    }
  });

  return list.sort((a, b) => a.name.localeCompare(b.name));
};

export const getCountryByCode = (code: string): CountryProfile => {
  const existing = MAJOR_COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  if (existing) return existing;
  
  const raw = ALL_COUNTRY_CODES[code.toUpperCase()];
  if (raw) {
    return {
      code: code.toUpperCase(),
      name: raw.name,
      flag: raw.flag,
      continent: raw.continent,
      currency: 'USD',
      crops: ['Maize', 'Potato', 'Wheat'],
      diseases: ['Maize Smut', 'Potato Late Blight']
    };
  }
  
  // Return India as default safe fallback
  return MAJOR_COUNTRIES[0];
};
